esphome:
  name: irl02
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

ota: !secret ota

api: !secret api

#remote_receiver:
#  pin:
#    number: GPIO15
#    inverted: true
#  dump:
#    - raw
#    - lg

sensor:
  - platform: adc
    pin: A0
    name: a0
#    attenuation: 11db
    internal: true
    update_interval: 1s
#  - platform: adc
#    pin: A1
#    name: a1
#     attenuation: 11db
#    internal: true
#    update_interval: 1s
#  - platform: adc
#    pin: A2
#    name: a2
#    attenuation: 11db
#    internal: true
#    update_interval: 1s
#  - platform: adc
#    pin: A3
#    name: a3
#    attenuation: 11db
#    internal: true
#    update_interval: 1s
#  - platform: adc
#    pin: 36
#    name: pin36
#    attenuation: 11db
#    internal: true
#    update_interval: 1s
#  - platform: adc
#    pin: 37
#    name: pin37
#    attenuation: 11db
#    internal: true
#    update_interval: 1s
#  - platform: adc
#    pin: 38
#    name: pin38
#    attenuation: 11db
#    internal: true
#    update_interval: 1s
#  - platform: adc
#    pin: 39
#    name: pin39
#    attenuation: 11db
#    internal: true
#    update_interval: 1s
#                                