substitutions:
  device: irl03
  name: Small Nightlight
  light_id: small_lightnight
  iot: !secret iot01
esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini

wifi: 
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${iot}
    gateway: !secret gateway
    subnet: !secret subnet

# Enable logging
logger:

ota: !secret ota

api: !secret api

wled:

light:
  - platform: neopixelbus
    pin: D4
    method: ESP8266_ASYNC_UART1
    num_leds: 7
    name: ${name}
    id: ${light_id}
    effects: !include nightlight_effects.yaml

remote_receiver:
  pin:
    number: GPIO5
    inverted: true

text_sensor:
  - platform: template
    name: "carmp3"
    id: template_carmp3
    internal: true
    
binary_sensor:
# Codes for the cheap "car mp3" remote
#  - platform: remote_receiver
#    internal: true
#    name: ir_car_ditto_detected
#    raw:
#      code: [8953, -2236, 571]
  - platform: remote_receiver
    internal: true
    name: ir_car_ch_minus_detected
    lg:
      data: 0x00FFA25D
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_ch
    lg:
      data: 0x00FF629D
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_ch_plus_detected
    lg:
      data: 0x00FFE21D
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_rewind_detected
    lg:
      data: 0x00FF22DD
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_fast_forward_detected
    lg:
      data: 0x00FF02FD
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_play_pause_detected
    lg:
      data: 0x00FFC23D
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_vol_minus_detected
    lg:
      data: 0x00FFE01F
      nbits: 32
    on_press:
      - then:
        - light.dim_relative:
            id: ${light_id}
            relative_brightness: -10%
  - platform: remote_receiver
    internal: true
    name: ir_car_vol_plus_detected
    lg:
      data: 0x00FFA857
      nbits: 32
    on_press:
      - then:
        - light.dim_relative:
            id: ${light_id}
            relative_brightness: 10%
  - platform: remote_receiver
    internal: true
    name: ir_car_eq_detected
    lg:
      data: 0x00FF906F
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_0_detected
    lg:
      data: 0x00FF6897
      nbits: 32
    on_press:
      then:
        - light.turn_on:
            id: ${light_id}
            effect: rainbow
  - platform: remote_receiver
    internal: true
    name: ir_car_100_detected
    lg:
      data: 0x00FF9867
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_200_detected
    lg:
      data: 0x00FFB04F
      nbits: 32
  - platform: remote_receiver
    internal: true
    name: ir_car_1_detected
    lg:
      data: 0x00FF30CF
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: fast rainbow
  - platform: remote_receiver
    internal: true
    name: ir_car_2_detected
    lg:
      data: 0x00FF18E7
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: slow random
  - platform: remote_receiver
    internal: true
    name: ir_car_3_detected
    lg:
      data: 0x00FF7A85
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: fast random
  - platform: remote_receiver
    internal: true
    name: ir_car_4_detected
    lg:
      data: 0x00FF10EF
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: twinkle effect
  - platform: remote_receiver
    internal: true
    name: ir_car_5_detected
    lg:
      data: 0x00FF38C7
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: random twinkle
  - platform: remote_receiver
    internal: true
    name: ir_car_6_detected
    lg:
      data: 0x00FF5AA5
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: fireworks
  - platform: remote_receiver
    internal: true
    name: ir_car_7_detected
    lg:
      data: 0x00FF42BD
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: flicker
  - platform: remote_receiver
    internal: true
    name: ir_car_8_detected
    lg:
      data: 0x00FF4AB5
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: random fireworks
  - platform: remote_receiver
    internal: true
    name: ir_car_9_detected
    lg:
      data: 0x00FF52AD
      nbits: 32
    on_press:
      then:
          - light.turn_on:
              id: ${light_id}
              effect: wled
