esphome:
  name: keypad01
  platform: ESP8266
  board: d1_mini
  includes:
    - keypad_sensor.h
  libraries:
    - "Keypad"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Keypad01 Fallback Hotspot"
    password: "CECsSvQDarhX"

captive_portal:

# Enable logging
logger:

ota: !secret ota

mqtt: !secret mqtt

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new KeypadSensor();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      name: "Keypad Sensor"
      
