esphome:
  name: neopixel01
  platform: ESP8266
  board: d1
  build_path: neopixel01
  platformio_options: {}
  esp8266_restore_from_flash: false
  includes: []
  libraries: []
wifi:
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  networks:
  - ssid: sardines2
    password: facefacefa
    priority: 0.0
  use_address: neopixel01.local
captive_portal: {}
logger:
  baud_rate: 115200
  tx_buffer_size: 512
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
#api:
#  password: albatross123$
#  port: 6053
#  reboot_timeout: 15min
ota:
  password: albatross123$
  safe_mode: true
  port: 8266
mqtt:
  broker: 192.168.2.131
  username: honestbroker
  password: honestbroker123$
light:
  - platform: neopixelbus
    pin: GPIO2
    method: ESP8266_ASYNC_UART1
    num_leds: 7
    name: "Nightlight"
    effects:
      # Customize parameters
      - random:
          name: "Slow Random"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 50
      - addressable_twinkle:
          name: Twinkle Effect
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
          name: Random Twinkle
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
          name: Flicker
