esphome:
  name: temphum01
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "sardines2"
  password: "facefacefa"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temphum01 Fallback Hotspot"
    password: "CECsSvQDarhX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "albatross123$"

ota:
  password: "albatross123$"
  
mqtt:
  broker: 192.168.2.131
  username: honestbroker
  password: honestbroker123$
  
i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  
sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 60s
   