esphome:
  name: test01
  platform: ESP32
  board: lolin_d32
  
wifi:
  networks:
  - ssid: sardines2
    password: facefacefa

captive_portal:

logger:

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True
  - id: bus_b
    sda: GPIO33
    scl: GPIO32
    scan: True

spi:
  miso_pin: GPIO12
  mosi_pin: GPIO13
  clk_pin: GPIO18

api:
  password: albatross123$
  port: 6053
  reboot_timeout: 15min

ota:
  password: albatross123$
  safe_mode: true
  port: 3232

as3935_spi:
  irq_pin: GPIO5
  cs_pin: GPIO19
  spike_rejection: 11
  noise_level: 4
  div_ratio: 32
  capacitance: 7

#deep_sleep:
#  run_duration: 10s
#  sleep_duration: 50s

sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 60s
  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
    distance:
      name: "Distance Storm"
  - platform: sht3xd
    temperature:
      name: "Temperature-2"
    humidity:
      name: "Humidity-2"
    address: 0x44
    update_interval: 60s

#esp32_ble_tracker:

binary_sensor:
  - platform: as3935
    name: "Storm Alert"
#  - platform: ble_presence
#    name: "BLE Test Presence"
  # Presence based on BLE Service UUID
  #- platform: ble_presence
  #  service_uuid: '11aa'
  #  name: "ESP32 BLE Tracker Test Service 16 bit"

