# Built on LolinD32 Breakout V1.1 board level ic2 not working
# i2c0 scl,sda markings are reversed
# i2c1 is miswired
substitutions:
  device: test
  name: Test
  iot: !secret iot03
  platform: ESP32
  board: lolin_d32

esphome:
  name: ${device}
  platform: ${platform}
  board: ${board}
#  includes:
#    - veml7700_custom_sensor.h
#    - sht31_custom_sensor.h
#  libraries:
#    - "https://github.com/adafruit/Adafruit_VEML7700"
#    - "https://github.com/adafruit/Adafruit_SHT31"

wifi: 
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${iot}
    gateway: !secret gateway
    subnet: !secret subnet

# Enable logging
logger:

ota: !secret ota

api: !secret api

# External connector bus IC20
i2c:
  - id: bus_a
    scl: GPIO22
    sda: GPIO21
    scan: True
  - id: bus_b
    scl: GPIO23
    sda: GPIO19
    scan: True

